config/routes.rb
Rails.application.routes.draw do
  
  
  get 'bookings/new'

  resources :bicycles
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
 resources :bookings
  
  root 'page#home'
  
  get 'page/home'

  get 'page/about'

  get 'page/faq'
  
  get 'page/contact'

end

app/models/bicycle.rb
class Bicycle < ActiveRecord::Base
    # By using this, we can access to the bookings and users through the bicycle model
    has_many :bookings
    has_many :users, through: :bookings
    
    def self.search(search_for)
        Bicycle.where("Title like ?", "%#{search_for}%") 
        #by using like  and "%#{search_for}%" it allows us  to search not only for the exact word 
    end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
    belongs_to :user
    belongs_to :bicycle
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    # By using this, we can access to the bookings and bicycles through the user model
    has_many :bookings
    has_many :bicycles, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :set_bicycle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,only: [:edit, :create, :update, :new]

  # GET /bicycles
  # GET /bicycles.json
  def index
    @bicycles = Bicycle.all
    if params[ :search]
      @bicycles = Bicycle.search(params[:search])
      @bicycles = @bicycles.order("created_at ASC")
    else
      @bicycles = @bicycles.order("created_at DESC")
    end
  end

  # GET /bicycles/1
  # GET /bicycles/1.json
  def show
  end

  # GET /bicycles/new
  def new
    @bicycle = Bicycle.new
  end

  # GET /bicycles/1/edit
  def edit
  end

  # POST /bicycles
  # POST /bicycles.json
  def create
    @bicycle = Bicycle.new(bicycle_params)

    respond_to do |format|
      if @bicycle.save
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully created.' }
        format.json { render :show, status: :created, location: @bicycle }
      else
        format.html { render :new }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicycles/1
  # PATCH/PUT /bicycles/1.json
  def update
    respond_to do |format|
      if @bicycle.update(bicycle_params)
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicycle }
      else
        format.html { render :edit }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bicycles/1
  # DELETE /bicycles/1.json
  def destroy
    @bicycle.destroy
    respond_to do |format|
      format.html { redirect_to bicycles_url, notice: 'Bicycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bicycle
      @bicycle = Bicycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bicycle_params
      params.require(:bicycle).permit(:title, :string, :description, :image_url, :price, :category, :available)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:destroy]
  
  def index
    @bookings=  Booking.all
  end
  
  def new
    @booking = Booking.new
    @booking.bicycle_id = params[:bike_id]
  end
  
  def create
    
    bicycle = Bicycle.find(booking_params[:bicycle_id])
    user_id = current_user.id
    days = booking_params[:days]
    
    if (bicycle.nil? or days.nil?)
      flash[:alert] = "Error creating the booking"
      redirect_to booking_url
    else
      
      @booking =  Booking.new ({:user_id=> user_id, :bicycle_id=>bicycle.id, :final_price=> booking_params[:final_price]})
      @booking.start = Time.now
      @booking.end = Time.now + days.to_i * 86400
      
      respond_to do |format|
        if @booking.save
          format.html { redirect_to bicycles_url, notice: 'Booking was successfully created.' }
          format.json { render :show, status: :created, location: @booking }
        else
          format.html { render :new }
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html {redirect_to bookings_url}
      format.json {head :no_content}
    end
    
  end
  
  def set_booking
    @booking = Booking.find(params[:id])
  end
  
  def booking_params
    params.require(:booking).permit( :bicycle_id, :final_price, :days)
  end
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  
  def home
  end

  def about
  end

  def faq
  end
  
  def contact
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/bicycles/_form.html.erb
<%= form_for(@bicycle) do |f| %>
  <% if @bicycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bicycle.errors.count, "error") %> prohibited this bicycle from being saved:</h2>

      <ul>
      <% @bicycle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
 
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.check_box :available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bicycles/edit.html.erb
<h1>Editing Bicycle</h1>

<%= render 'form' %>

<%= link_to 'Show', @bicycle %> |
<%= link_to 'Back', bicycles_path %>

app/views/bicycles/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(bicycles_path, :method => "get") do %>
  <%= text_field_tag :search, nil, :placeholder => "Search Bicycles by Title" %>
  <%= submit_tag "Search" %>
<% end %>


<div class="page-header">
  <h1>Listing Bicycles</h1>
</div>
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading"></div>
  <div class="panel-body">

<table class="table">

  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @bicycles.each do |bicycle| %>
      <tr>
        <td><%= bicycle.title %></td>
       
        <td><%= bicycle.description %></td>
        <td><%= bicycle.price %></td>
        <td><%= bicycle.category %></td>
        <td><%= bicycle.available %></td>
        <td><%= link_to 'Show', bicycle, class: 'btn btn-primary btn-xs' %></td>
        <% if (user_signed_in? and current_user.admin == true) %>
          <td><%= link_to 'Edit', edit_bicycle_path(bicycle), class: 'btn btn-primary btn-xs' %></td>
          <td><%= link_to 'Destroy', bicycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% elsif user_signed_in? %>
          <td colspan="2"><%= link_to 'Book it', new_booking_path(:bike_id=> bicycle.id), class: 'btn btn-success btn-xs' %></td>
         <% else %>
          <td colspan="2"></td>
         <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% if (user_signed_in? and current_user.admin == true) %>
  <div class="panel-footer">
  <%= link_to 'New Bicycle', new_bicycle_path, class: "btn btn-primary" %>
  </div>
<%end%>

</div>

app/views/bicycles/new.html.erb
<h1>New Bicycle</h1>

<%= render 'form' %>

<%= link_to 'Back', bicycles_path %>

app/views/bicycles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bicycle.title %>
</p>



<p>
  <strong>Description:</strong>
  <%= @bicycle.description %>
</p>



<p>
  <strong>Price:</strong>
  <%= @bicycle.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @bicycle.category %>
</p>

<p>
  <strong>Available:</strong>
  <%= @bicycle.available %>
</p>

<%= link_to 'Edit', edit_bicycle_path(@bicycle) %> |
<%= link_to 'Back', bicycles_path %>

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--This value is  hidden so users dont modify them-->
<%= hidden_field(:booking, :bicycle_id, :value => @booking.bicycle_id) %>

<!--Add info about the bicycle about to be booked-->
  <div class="field">
    <%= f.label :Bicycle_to_book %>
    <%= @booking.bicycle.title %>
    <%= @booking.bicycle.description %>
  </div>

  <div class="field">
    <%= f.label :days %><br>
    <%= number_field_tag 'booking[days]' %>
  </div>
  
<!--This input text is readonly, it is  modified when the number of days selected is chaged-->
  <div class="field">
    <%= f.label :final_price %><br>
    <%= f.text_field :final_price , :readonly =>true%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script type="text/javascript">
// Gets the price per day from the bicycle
  var bike_price = <%= @booking.bicycle.price %>
  
  // When the number of days changes this is triggered
  $("#booking_days").change(function(){
    var days = this.value
    final_price = days * bike_price
    // It changes the value of the final price to be displayed
    $("#booking_final_price").val(final_price)
  });
  
</script>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Bicycle</th>
      <th>Start</th>
      <th>End</th>
      <th>Final price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user_id %></td>
        <td><%= booking.bicycle_id %></td>
        <td><%= booking.start %></td>
        <td><%= booking.end %></td>
        <td><%= booking.final_price %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<h1>Booking a bicycle</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bikeapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <div id="main-container" class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Bike Rental</a>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", page_home_path %></li>
          <li><%= link_to "About", page_about_path %></li>
          <li><%= link_to "Bicycles", bicycles_path %></li>
          <li><%= link_to "Contact", page_contact_path %></li>
          <li><%= link_to "Faq", page_faq_path %></li>
          <% if (user_signed_in? and current_user.admin == true) %>
            <li><%= link_to "Booking History", bookings_path %></li>
            <li> <%= link_to "Profile", edit_user_registration_path %></li>
            <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% elsif user_signed_in? %>
            <li> <%= link_to "Profile", edit_user_registration_path %></li>
            <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li> <%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="row">
      <div class="col-sm-12">
        <%= yield %>
      </div>
    </div>
</div>

</body>
</html>

app/views/page/about.html.erb
<h1>About Us</h1>
<p>Welcome to our website Bike Rental. We are a young bike rental company based in Dublin 8. </p>

app/views/page/contact.html.erb
<h1>Contact</h1>
<p> 12a Clanbrassil Street Lower <br> Dublin 8, Ireland </p>

app/views/page/faq.html.erb
<h1>FAQ</h1>
<p>vitae tellus sagittis lalallala,
  eget aliquam vestibulum dictum volutpat lorem sed, nisl praesent sem ligula orci curae. Ut cras est eu, metus maecenas 
  tempor sed semper pulvinar id. Integer wisi nec fusce ac lacus luctus. Ipsum nisl sem lacus, quam nunc eget enim est, eros tortor et 
</p>

app/views/page/home.html.erb
<div class="jumbotron">
  <h1>Welcome to our website Bike Rental!!!</h1>
  <p>
  Lorem ipsum dolor sit amet, cras cras montes vitae, nibh suscipit morbi sodales vestibulum, urna vitae tellus sagittis, 
  eget aliquam vestibulum dictum volutpat lorem sed, nisl praesent sem ligula orci curae. Ut cras est eu, metus maecenas 
  tempor sed semper pulvinar id. Integer wisi nec fusce ac lacus luctus. Ipsum nisl sem lacus, quam nunc eget enim est, eros tortor et 
  . Integer mi sed dolor ridiculus sed sed, netus nulla eu dapibus nulla, elementum scelerisque vel odio erat et nisl. 
  Urna facilisis excepteur adipiscing. Vitae velit ipsum libero. Adipiscing aptent quisque vivamus in luctus, id aliquam id, leo 
  vitae blandit urna sed aliquam eros, risus neque metus in eget semper, eget eget lorem massa sed.
  </p>

</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bicycle %><br>
    <%= f.text_field :bicycle %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :decsription %><br>
    <%= f.text_area :decsription %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :availability %><br>
    <%= f.text_field :availability %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>